"""
Configuration with three layers (highest wins):
  1. settings.json in DATA_DIR      - edited from the app's Settings screen
  2. environment / .env             - server deployments
  3. bundled_keys.py                - keys baked into a desktop build (generated by build_exe, may be absent)
"""
from __future__ import annotations

import json
import os
import sys

from dotenv import load_dotenv

load_dotenv()

try:  # generated at build time; not committed
    from . import bundled_keys as _bundled  # type: ignore
except Exception:  # pragma: no cover
    _bundled = None


def _default_data_dir() -> str:
    if os.getenv("DATA_DIR"):
        return os.getenv("DATA_DIR")  # type: ignore[return-value]
    if getattr(sys, "frozen", False):  # PyInstaller build: keep data next to the user's profile
        base = os.getenv("LOCALAPPDATA") or os.getenv("XDG_DATA_HOME") or os.path.expanduser("~/.local/share")
        return os.path.join(base, "ResumeBuilder", "data")
    return os.path.join(os.path.dirname(os.path.dirname(__file__)), "data")


DATA_DIR = _default_data_dir()
os.makedirs(DATA_DIR, exist_ok=True)
SETTINGS_PATH = os.path.join(DATA_DIR, "settings.json")

SOFFICE_BIN = os.getenv("SOFFICE_BIN", "")
RESEARCH_DEPTH = os.getenv("RESEARCH_DEPTH", "deep")  # "deep" | "quick"

_DEFAULT_MODEL = "claude-opus-5"
_DEFAULT_FAST_MODEL = "claude-sonnet-5"


def _settings() -> dict:
    try:
        with open(SETTINGS_PATH, encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return {}


def save_settings(values: dict) -> dict:
    cur = _settings()
    for k, v in values.items():
        if v is None:
            continue
        v = str(v).strip()
        if v == "":
            cur.pop(k, None)
        else:
            cur[k] = v
    with open(SETTINGS_PATH, "w", encoding="utf-8") as f:
        json.dump(cur, f, indent=1)
    return cur


def _get(name: str, default: str = "") -> str:
    s = _settings()
    if s.get(name):
        return s[name]
    if os.getenv(name):
        return os.getenv(name)  # type: ignore[return-value]
    if _bundled is not None and getattr(_bundled, name, ""):
        return getattr(_bundled, name)
    return default


def anthropic_key() -> str:
    return _get("ANTHROPIC_API_KEY")


def tavily_key() -> str:
    return _get("TAVILY_API_KEY")


def model() -> str:
    return _get("CLAUDE_MODEL", _DEFAULT_MODEL)


def fast_model() -> str:
    return _get("CLAUDE_FAST_MODEL", _DEFAULT_FAST_MODEL)


def key_sources() -> dict:
    """Where each key comes from (for the Settings screen), never the key itself."""
    def src(name):
        if _settings().get(name):
            return "settings"
        if os.getenv(name):
            return "environment"
        if _bundled is not None and getattr(_bundled, name, ""):
            return "bundled"
        return "missing"
    return {"ANTHROPIC_API_KEY": src("ANTHROPIC_API_KEY"), "TAVILY_API_KEY": src("TAVILY_API_KEY")}


def missing_keys() -> list[str]:
    out = []
    if not anthropic_key():
        out.append("ANTHROPIC_API_KEY")
    if not tavily_key():
        out.append("TAVILY_API_KEY")
    return out


# Backwards-compatible module attributes used in a few places
class _Dyn:
    @property
    def CLAUDE_MODEL(self):  # noqa: N802
        return model()

    @property
    def CLAUDE_FAST_MODEL(self):  # noqa: N802
        return fast_model()


_dyn = _Dyn()


def __getattr__(name: str):  # module-level dynamic attributes (PEP 562)
    if name in ("CLAUDE_MODEL", "CLAUDE_FAST_MODEL"):
        return getattr(_dyn, name)
    if name == "ANTHROPIC_API_KEY":
        return anthropic_key()
    if name == "TAVILY_API_KEY":
        return tavily_key()
    raise AttributeError(name)
