"""Write backend/app/bundled_keys.py from .env (or the environment) so a desktop build carries default keys."""
import os
import re
import sys

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
env: dict[str, str] = {}
env_path = os.path.join(root, ".env")
if os.path.exists(env_path):
    for line in open(env_path, encoding="utf-8"):
        if line.strip().startswith("#"):
            continue
        m = re.match(r"\s*([A-Z_]+)\s*=\s*(.*?)\s*$", line)
        if m:
            env[m.group(1)] = m.group(2).strip().strip('"').strip("'")
keys = ("ANTHROPIC_API_KEY", "TAVILY_API_KEY", "CLAUDE_MODEL", "CLAUDE_FAST_MODEL")
out = os.path.join(root, "backend", "app", "bundled_keys.py")
with open(out, "w", encoding="utf-8") as f:
    f.write("# generated by tools/bake_keys.py - do not commit\n")
    for k in keys:
        f.write(f"{k} = {(os.getenv(k) or env.get(k, ''))!r}\n")
print("bundled keys:", {k: ("set" if (os.getenv(k) or env.get(k)) else "-") for k in keys[:2]}, "->", os.path.relpath(out, root))
